apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-uploads-pvc
  namespace: capstone
spec:
  accessModes:
    - ReadWriteMany   # Multiple pods need read access
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
