global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "inference-service"
    static_configs:
      - targets: ["inference-service:8001"]
    metrics_path: /metrics

  - job_name: "model-registry"
    static_configs:
      - targets: ["model-registry:8002"]
    metrics_path: /metrics

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8080"]
    metrics_path: /actuator/prometheus
