apiVersion: v1
kind: Secret
metadata:
  name: capstone-secrets
  namespace: capstone
type: Opaque
stringData:
  JWT_SECRET: "capstone-secret-key-change-in-production-must-be-256-bits-long!!"
  DB_PASSWORD: "capstone123"
  GRAFANA_PASSWORD: "admin123"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: capstone
type: Opaque
stringData:
  POSTGRES_USER:     "capstone"
  POSTGRES_PASSWORD: "capstone123"
  POSTGRES_DB:       "model_registry"
